### ISSUE TITLE
Pads instead of smd MXC6255XC

### ISSUE THREAD

**Issue by Matthew-Klock** [IlliniHyperloopComputing/PCB#9]
Hey, 
So I looked over the package that I approved for the MXC6255XC and I realized that it wasn't entirely right. You used pads, which are basically through holes in the board. Please replace the pads with SMD.

**Comment by 1019gene** [comment]
Should it be like this? If so, what are the holes in figure 7? Or do I not need to do anything with those?
<img width="1440" alt="screen shot 2018-09-26 at 2 45 09 pm" src="https://user-images.githubusercontent.com/43457465/46105173-f4bdbd80-c19a-11e8-81aa-70318ef1b3ab.png">
<img width="337" alt="screen shot 2018-09-26 at 2 45 24 pm" src="https://user-images.githubusercontent.com/43457465/46105174-f4bdbd80-c19a-11e8-99a5-ed374908819e.png">

**Comment by Matthew-Klock** [comment]
Yes, perfect, submit the pull request. Figure 7 is showing where the actual pins will be, figure 8 is showing where the pads should be.  The pads will be bigger than the pins, you can read about it here: https://electronics.stackexchange.com/questions/222894/what-is-the-meaning-of-landing-pattern-in-designing-ic-footprint

**Comment by 1019gene** [comment]
Uploaded!
